module.exports = [
  // 'Cultist',
  // 'Divine',
  // 'Dusk',
  // 'Enlightened',
  // 'Elderwood',
  // 'Exile',
  // 'Fortune',
  // 'Mystic',
  // 'Moonlight',
  // 'Ninja',
  // 'Spirit',
  // 'The Boss',
  // 'Tormented',
  // 'Warlord',
  // 'Adept',
  // 'Assassin',
  // 'Bagarreur',
  // 'Dazzler',
  // 'Duelist',
  // 'Emperor',
  // 'Hunter',
  // 'Keeper',
  // 'Mage',
  // 'Shade',
  // 'Sharpshooter',
  // 'Initiateur'
]